### ISSUE TITLE
SyntaxError: Invalid assignment

### ISSUE THREAD

**Issue by aijingsun6** [nebulasio/nebPay#37]
我遇到的问题是，直接npm install nebpay.js --save
然后直接 import {NebPay} from 'nebpay.js';(typescript)

在编译的时候报错：
Build Failed: GulpUglifyError: unable to minify JavaScript
Caused by: SyntaxError: Invalid assignment
File: /project.js

但是 nebulas 这个依赖就没有问题

**Comment by aijingsun6** [comment]
使用的是cocos
全部堆栈如下：
Build Failed: GulpUglifyError: unable to minify JavaScript
Caused by: SyntaxError: Invalid assignment
File: /project.js
Line: 29239
at createError (/Applications/CocosCreator.app/Contents/Resources/app.asar/node_modules/gulp-uglify/lib/create-error.js:6:14)
    at apply (/Applications/CocosCreator.app/Contents/Resources/app.asar/node_modules/gulp-uglify/node_modules/lodash/_apply.js:16:25)
    at wrapper (/Applications/CocosCreator.app/Contents/Resources/app.asar/node_modules/gulp-uglify/node_modules/lodash/_createCurry.js:41:12)
    at /Applications/CocosCreator.app/Contents/Resources/app.asar/node_modules/gulp-uglify/lib/minify.js:54:15
    at DestroyableTransform._transform (/Applications/CocosCreator.app/Contents/Resources/app.asar/node_modules/gulp-uglify/composer.js:10:23)
    at DestroyableTransform.Transform._read (/Applications/CocosCreator.app/Contents/Resources/app.asar/node_modules/readable-stream/lib/_stream_transform.js:184:10)
    at DestroyableTransform.Transform._write (/Applications/CocosCreator.app/Contents/Resources/app.asar/node_modules/readable-stream/lib/_stream_transform.js:172:83)
    at doWrite (/Applications/CocosCreator.app/Contents/Resources/app.asar/node_modules/readable-stream/lib/_stream_writable.js:418:64)
    at writeOrBuffer (/Applications/CocosCreator.app/Contents/Resources/app.asar/node_modules/readable-stream/lib/_stream_writable.js:407:5)
    at DestroyableTransform.Writable.write (/Applications/CocosCreator.app/Contents/Resources/app.asar/node_modules/readable-stream/lib/_stream_writable.js:334:11)
    at Async.series.t (/Applications/CocosCreator.app/Contents/Resources/app.asar/editor/core/builder.js:1:3024)
    at /Applications/CocosCreator.app/Contents/Resources/app.asar/node_modules/async/lib/async.js:726:13
    at /Applications/CocosCreator.app/Contents/Resources/app.asar/node_modules/async/lib/async.js:52:16
    at /Applications/CocosCreator.app/Contents/Resources/app.asar/node_modules/async/lib/async.js:264:21
    at /Applications/CocosCreator.app/Contents/Resources/app.asar/node_modules/async/lib/async.js:44:16
    at /Applications/CocosCreator.app/Contents/Resources/app.asar/node_modules/async/lib/async.js:723:17
    at /Applications/CocosCreator.app/Contents/Resources/app.asar/node_modules/async/lib/async.js:167:37
    at Gulp.doneCallback (/Applications/CocosCreator.app/Contents/Resources/app.asar/editor/core/gulp-build.js:1:17460)
    at Gulp.Orchestrator.stop (/Applications/CocosCreator.app/Contents/Resources/app.asar/node_modules/orchestrator/index.js:150:9)
